version: '3.8'

services:
  # nestjs_api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     PORT: 3000
  #     NODE_ENV: development
  #   volumes:
  #     - ./src:/usr/src/app/src
  spss_db:
    image: mysql:8.0.40
    container_name: spss_db
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    volumes:
      - mydb:/var/lib/mysql:rw
      - ./mysql-db:/docker-entrypoint-initdb.d/
      # - ./db:/docker-entrypoint-initdb.d/triggers/create_trigger.sql
    networks:
      - default
      
volumes:
  mydb:
networks:
  default:

#docker-compose -f Docker-compose.yaml up --build -d

#QUERY
#User
#docker exec -it <container_name> mysql -u <username> -p
#docker exec -it spss_db mysql -u testuser -p
#root
#docker exec -it spss_db mysql -u root -p

#use <dbname>;
#SELECT * FROM user;
